language: go
sudo: false
matrix:
  include:
  - os: osx
    go: 1.12.x
  - os: linux
    go: 1.12.x
notifications:
  email: false
script:
- go get -u -v github.com/go-task/task/cmd/task && task build
